### ISSUE TITLE
Saasc 2.4.0 installation error - #include <vector>

### ISSUE THREAD

**Issue by ricvillagrana** [sass/sassc-ruby#225]
Hi, when I try to do `bundle install` this dependency is unable to be installed. How can I solve this issue?

OS: `macOS Big Sur v11.5.2`
Ruby version: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]`
Rails version: `5.2.6`

```
Installing sassc 2.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/ricardo/.rvm/gems/ruby-2.7.4/gems/sassc-2.4.0/ext
/Users/ricardo/.rvm/rubies/ruby-2.7.4/bin/ruby -I /Users/ricardo/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0 -r ./siteconf20210813-15067-5gceb3.rb extconf.rb
creating Makefile

current directory: /Users/ricardo/.rvm/gems/ruby-2.7.4/gems/sassc-2.4.0/ext
make "DESTDIR=" clean

current directory: /Users/ricardo/.rvm/gems/ruby-2.7.4/gems/sassc-2.4.0/ext
make "DESTDIR="
compiling ./libsass/src/ast.cpp
In file included from ./libsass/src/memory.hpp:8,
                 from ./libsass/src/sass.hpp:55,
                 from ./libsass/src/ast.cpp:3:
./libsass/src/memory/allocator.hpp:8:10: fatal error: vector: No such file or directory
    8 | #include <vector>
      |          ^~~~~~~~
compilation terminated.
make: *** [ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/ricardo/.rvm/gems/ruby-2.7.4/gems/sassc-2.4.0 for inspection.
Results logged to /Users/ricardo/.rvm/gems/ruby-2.7.4/extensions/x86_64-darwin-20/2.7.0/sassc-2.4.0/gem_make.out

An error occurred while installing sassc (2.4.0), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.4.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootstrap-email was resolved to 1.0.0.alpha4, which depends on
    sassc
```

Thanks in advance for the help. Let me know if you need more information.

**Comment by ahorek** [comment]
I'm not familiar with the Mac ecosystem, but the error is definitely related to their specific compiler. Maybe they need some special build flags or the compiler version is simply outdated. Try to use a different one if possible.

**Comment by dersnek** [comment]
Getting the same error on Debian running in WSL.
OS: `Windows 11 21H2 build 22000.556`
WSL OS: `Pengwin 11 v. 21.12.0` (basically Debian)
Ruby version: `2.7.1 [x86_64-linux]`
Rails version: `6.1.4.6`

My error:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/ext
/home/dersnek/.asdf/installs/ruby/2.7.1/bin/ruby -I /home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0
creating Makefile

current directory: /home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/ext
make "DESTDIR=" clean

current directory: /home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/ext
make "DESTDIR="
compiling ./libsass/src/ast.cpp
make: g++: Permission denied
make: *** [Makefile:237: ast.o] Error 127

make failed, exit code 2

Gem files will remain installed in /home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/sassc-2.4.0 for
inspection.
Results logged to
/home/dersnek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sassc-2.4.0/gem_make.out

An error occurred while installing sassc (2.4.0), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.4.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootstrap was resolved to 4.6.0, which depends on
    sassc-rails was resolved to 2.1.2, which depends on
      sassc
```

It was building fine on Rails `5.2.2.1`, started failing after upgrade to 6.1.

**Comment by dangquangthai** [comment]
I got the same error with:
- rails 7.1.4
- sass-rails (6.0.0) 
- ruby 3.1.2
- MacOS Sequoia (Version 15.0)
- `libsass` and `gcc` already installed via brew

```shell
Fetching gem metadata from https://rubygems.org/.........
Installing sassc 2.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/thaidang/.rvm/gems/ruby-3.1.2@sia/gems/sassc-2.4.0/ext
/Users/thaidang/.rvm/rubies/ruby-3.1.2/bin/ruby extconf.rb
creating Makefile

current directory: /Users/thaidang/.rvm/gems/ruby-3.1.2@sia/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20240927-12423-ir9f8b sitelibdir\=./.gem.20240927-12423-ir9f8b clean

current directory: /Users/thaidang/.rvm/gems/ruby-3.1.2@sia/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20240927-12423-ir9f8b sitelibdir\=./.gem.20240927-12423-ir9f8b
compiling ./libsass/src/ast.cpp
In file included from ./libsass/src/ast.cpp:3:
In file included from ./libsass/src/sass.hpp:55:
In file included from ./libsass/src/memory.hpp:8:
./libsass/src/memory/allocator.hpp:8:10: fatal error: 'vector' file not found
    8 | #include <vector>
      |          ^~~~~~~~
1 error generated.
make: *** [ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/thaidang/.rvm/gems/ruby-3.1.2@sia/gems/sassc-2.4.0 for inspection.
Results logged to /Users/thaidang/.rvm/gems/ruby-3.1.2@sia/extensions/arm64-darwin-23/3.1.0/sassc-2.4.0/gem_make.out
```

**Comment by dangquangthai** [comment]
@AJ-Ayush  I resolved this by deleting the directory `/Library/Developer/CommandLineTools/` on my iMac. After that, It automatically installs the new dev tool and then run `bundle install`

**Comment by crnastena** [comment]
My issue was with how ruby was built when installing it with asdf. Two different versions of ruby had different output for compilers:

```shell
# ruby 3.3.3 compiler check
ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
"usr/bin/clang"
"false"
```

```shell
# ruby 3.3.4 compiler check
ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
"clang"
"clang++"
```

After some searching I came across [ruby-build](https://github.com/rbenv/ruby-build/blob/master/README.md), which is used by `asdf-ruby` plugin, and ability to specify compiler paths. So I reinstalled ruby:

```shell
asdf uninstall ruby 3.3.3
CC="clang" CXX="clang++" asdf install ruby 3.3.3
```

After that `sassc` was built properly.

I am not sure how this works with different ruby managers like `rvm` and `rbenv`.

**Comment by ntritin62** [comment]
> ```shell
> ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
> ```

that works for me. thank you very much

**Comment by ntritin62** [comment]
> My issue was with how ruby was built when installing it with asdf. Two different versions of ruby had different output for compilers:
> 
> ```shell
> # ruby 3.3.3 compiler check
> ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
> "usr/bin/clang"
> "false"
> ```
> 
> ```shell
> # ruby 3.3.4 compiler check
> ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
> "clang"
> "clang++"
> ```
> 
> After some searching I came across [ruby-build](https://github.com/rbenv/ruby-build/blob/master/README.md), which is used by `asdf-ruby` plugin, and ability to specify compiler paths. So I reinstalled ruby:
> 
> ```shell
> asdf uninstall ruby 3.3.3
> CC="clang" CXX="clang++" asdf install ruby 3.3.3
> ```
> 
> After that `sassc` was built properly.
> 
> I am not sure how this works with different ruby managers like `rvm` and `rbenv`.

that works for me. thank you very much.

**Comment by whyayen** [comment]
> ```shell
> asdf uninstall ruby 3.3.3
> CC="clang" CXX="clang++" asdf install ruby 3.3.3
> ```
> 
> After that `sassc` was built properly.
> 
> I am not sure how this works with different ruby managers like `rvm` and `rbenv`.

This also works for me, thanks 🙏🏾.  And installation via `rbenv` is as same as `asdf` (`rbenv` uses `ruby-build` to install specific version ruby too).

**Comment by shellandbull** [comment]
@crnastena Do you know what the equivalent would be for `rvm` ? I am running into the same issue

**Comment by whyayen** [comment]
> @crnastena Do you know what the equivalent would be for `rvm` ? I am running into the same issue

@shellandbull  `rvm` seems to provide the `--with-gcc` option. maybe you can give it a try.
https://github.com/rvm/rvm/blob/e732b5a46aaab81fb0988c6292d526385d62052b/scripts/functions/build#L20

**Comment by ozmullins** [comment]
> @AJ-Ayush I resolved this by deleting the directory `/Library/Developer/CommandLineTools/` on my iMac. After that, It automatically installs the new dev tool and then run `bundle install`

This fixed for me.

Though I did:
* `rm -rf /Library/Developer/CommandLineTools/`
* `xcode-select --install`
* `rbenv install 3.3.4`
* `bundle install`

**Comment by kurochkinSergei** [comment]
I had the following situation
```
# ruby v3.2.5 compiler check
ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
"clang"
"false"
```

[This fix](https://github.com/sass/sassc-ruby/issues/225#issuecomment-2391209718) but without `asdf` worked for me

```
rbenv uninstall 3.2.5
CC="clang" CXX="clang++" rbenv install 3.2.5
```

**Comment by cherkanovart** [comment]
> > @crnastena Do you know what the equivalent would be for `rvm` ? I am running into the same issue
> 
> @shellandbull RVM seems to provide the `--with-gcc` option. maybe you can give it a try. https://github.com/rvm/rvm/blob/e732b5a46aaab81fb0988c6292d526385d62052b/scripts/functions/build#L20

Thank you! if you're using rvm:  `rvm reinstall 3.X.X --with-gcc`

**Comment by briciocode** [comment]
Error:
```
Fetching gem metadata from https://rubygems.org/........
Installing sassc 2.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/briciocardoso/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sassc-2.4.0/ext
/Users/briciocardoso/.rbenv/versions/3.3.5/bin/ruby extconf.rb
creating Makefile

current directory: /Users/briciocardoso/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20250109-40459-qzp70v sitelibdir\=./.gem.20250109-40459-qzp70v clean

current directory: /Users/briciocardoso/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20250109-40459-qzp70v sitelibdir\=./.gem.20250109-40459-qzp70v
compiling ./libsass/src/ast.cpp
make: *** [ast.o] Error 1

make failed, exit code 2

....

An error occurred while installing sassc (2.4.0), and Bundler cannot continue.

In Gemfile:
  sass-rails was resolved to 6.0.0, which depends on
    sassc-rails was resolved to 2.1.2, which depends on
      sassc
```

That worked for me:

```
rm -rf /Library/Developer/CommandLineTools/
xcode-select --install
rbenv uninstall 3.3.5
CC="clang" CXX="clang++" rbenv install 3.3.5
bundle install
```

**Comment by Ahmed-Salama96** [comment]
Solved on my side by reinstalling the ruby version like this

```
rbenv uninstall 3.2.4
CC="clang" CXX="clang++" rbenv install 3.2.4
```

**Comment by remino** [comment]
I’m using [_mise_](https://mise.jdx.dev). I am trying this:

```sh
CC="clang" CXX="clang++" mise install ruby 3.4.2
```

But installing `sassc` after (and `eventmachine`) still both fail. `sassc` fails the same way than described above: https://github.com/sass/sassc-ruby/issues/225#issuecomment-2580196962

How can I verify if the environment variables in my command were passed through the build correctly?

**Edit:** Never mind. I found a way, but passing env vars seems to have no effect with mise:

```
❯ ruby -e 'puts RbConfig::CONFIG["CC"]; puts RbConfig::CONFIG["CXX"]'
clang
false
```

**Edit 2:** Even with `ruby-build,` it doesn’t work:

```
❯ export CC=clang CXX=clang++
❯ ruby-build 3.4.2 ~/3.4.2
❯ cd ~/3.4.2
❯ cd bin
❯ ./ruby -e 'puts RbConfig::CONFIG["CC"]; puts RbConfig::CONFIG["CXX"]'
clang
false
```

How come setting CXX works for the rest of you? 🤨

**Edit 3:** Well, huh. Found this [bug](https://bugs.ruby-lang.org/issues/21111) filed just 15 days ago. It’s about `ruby-build` quietly setting `CXX` to `false` when something fails. Found out I also had to wipe my command-line tools:

```
❯ rm -rf /Library/Developer/CommandLineTools/
❯ xcode-select --install
❯ export CC=clang CXX=clang++
❯ ruby-build 3.4.2 ~/3.4.2
❯ cd ~/3.4.2/bin
❯ ./ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
"clang"
"clang++ -std=gnu++11”
```

That also fixed the issue I was having with _mise_:

```
❯ mise install ruby
❯ ./ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]' -e'p RbConfig::CONFIG["CXX"]'
"clang"
"clang++ -std=gnu++11”
❯ gem install sassc # Worked!
```

Sorry for updating my comments several times—didn’t want to notify everyone with a series of comments. I hope this helps someone stuck with the same problem using _mise_.
